name: wildfire_powerlines

services:
  wildfire:
    build:
      context: .
      dockerfile: Dockerfile
    image: wildfire-pl:cpu
    working_dir: /code
    volumes:
      - .:/code
    environment:
      - GEOPANDAS_IO_ENGINE=pyogrio
      - PROJ_NETWORK=ON
      - NO_ALBUMENTATIONS_UPDATE=1
    entrypoint: ["/bin/sh","-lc","sleep infinity"]
    stdin_open: true
    tty: true
